### PR TITLE
Support Julia >1.7 on the binding generator

### PR DESCRIPTION
**Pull request by mofeing**

### CODE REVIEW

**Comment by vchuravy** [comment]
Does that reliably work?  I thought I tried it and struggled with it and 1.7 is what Yggdrasil uses

**Comment by mofeing** [comment]
I've tried both in Julia 1.7 and 1.10, and it works. Not an expert but adding the revision number to the LLVM versions fixed the build on Julia 1.10.

**Comment by vchuravy** [comment]
It might not work on 1.9 then. LGTM

**Comment by mofeing** [comment]
Tested on Julia 1.8 and 1.9: works perfectly.

**Pull request merged**
